### ISSUE TITLE
[Feat]Account Status Overview  제작, Network 그래프 명세작성 및 개발

### ISSUE THREAD

**Issue by breakpack** [AegisLenz/AegisLenz-FE#33]
## 🔥 Issue
그리드 안의 내용 제작

## ✅ TODO
- [x] ]Account Status Overview  제작
- [ ] Network 그래프 명세작성
- [ ] Network 그래프 그리기
